name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conda (Miniforge)
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          activate-environment: solarwave
          environment-file: mamba_environment.yml
          auto-activate-base: false
          use-mamba: true

      - name: Run tests
        shell: bash -l {0}
        run: pytest
